manifest:
  version: 0.8

  projects:
    - name: zephyr
      # revision: v4.2.0
      # url: https://github.com/zephyrproject-rtos/zephyr
      revision: driver/ch32v30x_ethernet_fixes
      url: https://github.com/BOJIT/zephyr

      import:
        file: west.yml
        path-prefix: deps
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - hal_wch

  self:
    path: app
