name: Build uPTP Firmware

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:
    inputs:
      sdk_version:
        description: Zephyr SDK version (use LATEST for the latest version)
        required: true
        default: LATEST

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        board: ["ch32v307evt", "uptp_v1", "nucleo_f767zi"]
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.vnumbers.outputs.release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: software/deps
          key: cache-deps-${{ hashFiles('software/app/west.yml') }}

      - name: Determine SDK version
        id: sdk-version
        run: |
          SDK_VERSION="${{ github.event.inputs.sdk_version || 'LATEST' }}"
          if [ "$SDK_VERSION" = "LATEST" ]; then
            LATEST_VERSION=$(curl -s https://api.github.com/repos/zephyrproject-rtos/sdk-ng/releases/latest | jq -r .tag_name | sed 's/v//')
            echo "SDK_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT
            echo "Using latest Zephyr SDK version: $LATEST_VERSION"
          else
            echo "SDK_VERSION=$SDK_VERSION" >> $GITHUB_OUTPUT
            echo "Using specified Zephyr SDK version: $SDK_VERSION"
          fi

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          base-path: software
          app-path: app
          toolchains: arm-zephyr-eabi:riscv64-zephyr-elf

          sdk-version: ${{ steps.sdk-version.outputs.SDK_VERSION }}

    #   - name: Install user packages
    #     working-directory: sofware/app
    #     run: |
    #         pip install -r requirements.txt

      - name: Build for target board
        working-directory: software/app
        run: |
          west build -b ${{matrix.board}} --pristine -- -DBOARD_ROOT=.

      - name: Build memory report
        working-directory: software/app
        run: |
          west build -t ram_report
          west build -t rom_report
